### ISSUE TITLE
Support browsing from the local file system

### ISSUE THREAD

**Issue by invisnet** [getstattic/stattic#11]
Other than translating bare links to the default index file, there's no technical reason to run a local web server to browse a static site.

If there were an option (e.g. `--dev`, ) which:

- used relative paths for internal links (e.g. `--relative-paths`), and
- linked directly to `index.html` (e.g. `--direct-links`)

it would greatly simplify development.

**Comment by robertdevore** [comment]
@invisnet thanks for bringing this up. I've been working on this setup and have it just about ready.

I updated the script to default to a `--dev` build using relative paths and direct links. This way you'll be able to just run it like this:

```
python3 stattic.py --output ~/Documents/demo --posts-per-page 5 --minify
```

And when you're ready to build it for production, you'll specify the `--site-url` like this:

```
python3 stattic.py --output ~/Documents/demo --posts-per-page 5 --minify --site-url "https://demo.stattic.site"
```

I'm doing some final testing and adding this to the repo shortly, so I'll be closing this issue out. Feel free to open a new issue if you run into any problems with the new update.

FWIW it'll be v0.0.6 added in the releases once it's ready 🤘
